# Generated by Django 5.2.1 on 2025-05-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.URLField(max_length=512),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("EXPIRED", "Expired"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
