# Generated by Django 5.2.1 on 2025-05-19 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authors", "0001_initial"),
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookauthor",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_authors",
                to="books.book",
            ),
        ),
        migrations.AddIndex(
            model_name="bookauthor",
            index=models.Index(
                fields=["book", "author"], name="authors_boo_book_id_2143b5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bookauthor",
            unique_together={("book", "author")},
        ),
    ]
