# Generated by Django 5.2.1 on 2025-05-19 10:50

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "cover",
                    models.CharField(
                        choices=[("Hard", "Hardcover"), ("Soft", "Softcover")],
                        default="Hard",
                        max_length=4,
                    ),
                ),
                ("inventory", models.IntegerField()),
                ("daily_fee", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=books.models.book_image_file_path,
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="books",
                        through="authors.BookAuthor",
                        to="authors.author",
                    ),
                ),
            ],
        ),
    ]
