# Generated by Django 5.2.1 on 2025-05-21 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0002_alter_borrowing_book"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowing",
            options={
                "ordering": ["-actual_return_date", "expected_return_date"],
                "verbose_name_plural": "borrowings",
            },
        ),
    ]
